### ISSUE TITLE
CONTROLEUR/ Definir les roles

### ISSUE THREAD

**Issue by RemiLelaidier** [RemiLelaidier/SIOC-Silex#15]
Il faut definir les roles des utilisateurs eleve professeur et admin

Tout cela se passe dans le security service provider de Silex dans le controleur. ->Documentation

Ensuite, il faut les implementer dans les roles grace a is_granted dans le layout(Le code a deja ete balise grace aux commentaire)

**Comment by JDLSousa** [comment]
Fait.
