### ISSUE TITLE
MODELE/VUE/ Debug de l'afiichage des chiffre et date

### ISSUE THREAD

**Issue by RemiLelaidier** [RemiLelaidier/SIOC-Silex#21]

**Comment by JDLSousa** [comment]
Pendant mon trajet de train, je me suis dit que si jamais, on ne trouve pas le bug, on peut toujours utiliser ce qu'on a vu en cours avec Vincent, la date devient une key puis le définir en tant qu'item.

**Comment by RemiLelaidier** [comment]
Les booleens aussi ne marche pas
