### ISSUE TITLE
CONTROLEUR/ Route '/' -> Envoyer les donnees pour les widgets

### ISSUE THREAD

**Issue by RemiLelaidier** [RemiLelaidier/SIOC-Silex#43]

**Comment by RemiLelaidier** [comment]
-Envoyer toutes les activites de l'utilisateur connecte
-Envoyer la liste des professeurs
-Envoyer le nb de competences valides par l'eleve (
      CompetenceDAO->findNbByEleve($iddeleleve)
)
-Envoyer la promo de l'eleve(
      PromotionDAO->findByEleve($iddeleleve)
)

**Comment by vidavenel** [comment]
SELECT COUNT(DISTINCT ass.ass_competence) 
FROM Associe as ass, Activite as act 
WHERE ass.ass_activite = act.act_id
AND act.act_eleve =
