### ISSUE TITLE
REDAC/ Rentrer les competences

### ISSUE THREAD

**Issue by JDLSousa** [RemiLelaidier/SIOC-Silex#45]
Le Tableau : https://lookaside.fbsbx.com/file/bts_sio_e6_tableau_synthese2015.0.xls?token=AWwgORCgVzy78_DFs-pfv9XZRKth6kOiuXT6roVa6UMvH0vWAFlqP2MnVVCgBi_xsoBcrQ0m9NsFViSto6mRPRQXXhOhS8l6_biAWZKNsMAcIA

_*Il y a les deux options, donc assurez-vous de bien copier la partie SLAM !_

**Comment by JDLSousa** [comment]
Done

**Comment by RemiLelaidier** [comment]
TODO => Fichier SQL pour charger les competences

**Comment by JDLSousa** [comment]
Je peux le faire sans soucis, je l'ai déjà fait pour les rentrer, donc bon.

Je dois l'avoir, quelque part dans mes documents d'ailleurs.
