### ISSUE TITLE
auto deploiement

### ISSUE THREAD

**Issue by vidavenel** [RemiLelaidier/SIOC-Silex#5]
Bonjour a tous,
Merci de m'accorder des droits admin sur le dépôt, le script pour le déploiement est OK cela vous permettra de synchroniser le serveur automatiquement.
Merci

**Comment by RemiLelaidier** [comment]
Salut,

Comment on fait pour t'accorder les droits admin ?

Envoyé de mon ASUS

-------- Message d'origine --------
De :vidavenel notifications@github.com
Envoyé :Sun, 14 Feb 2016 09:46:17 +0100
À :RemiLelaidier/SIOC-Silex SIOC-Silex@noreply.github.com
Sujet :[SIOC-Silex] auto deploiement (#5)

Bonjour a tous,
Merci de m'accorder des droits admin sur le dépôt, le script pour le déploiement est OK cela vous permettra de synchroniser le serveur automatiquement.
Merci

---

Reply to this email directly or view it on GitHub:
https://github.com/RemiLelaidier/SIOC-Silex/issues/5

**Comment by vidavenel** [comment]
il me semble que c'est dans le menu settings onglet collaborator

**Comment by RemiLelaidier** [comment]
J'ai regardé, tu y as acces normalement

Envoyé de mon ASUS

-------- Message d'origine --------
De :vidavenel notifications@github.com
Envoyé :Sun, 14 Feb 2016 10:14:26 +0100
À :RemiLelaidier/SIOC-Silex SIOC-Silex@noreply.github.com
Ci :RemiLelaidier r.lelaidier@hotmail.fr
Sujet :Re: [SIOC-Silex] auto deploiement (#5)

il me semble que c'est dans le menu settings onglet collaborator

---

**Comment by vidavenel** [comment]
Non j'ai rien, c'est pas grave tu va le faire:

- Dans webhook tu ajoutes 

> adresseDuServeur/deploy_pt.php

- dans deploy key : 

> ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7A2IR8ch8OApMgQi2u5KvDWXANEJLJAjHDrqmcVHM7Kd1qhIxTJI1gvZlXuDcw85+Ll9OjDY6M8wBlwhjDPqHF34mtIv51KkSY3j4YVbgnv8ojlVGVAN8ORn1tN5Yvgu/K7cTEq5yGc2sP0zPIalLh9ndodjgMuxz4r4kK/yn0und3IIkLLKsZAC/7aRWOTEWuk7IbWqKJmWSJe9UH0Rh//yJdKUSXXnXzDCU5j0UwcEKXTUASSAXs9eQMSKj922lp5GSs2KsZu7zi/7THJTYC/0BVzc3tJv0PbJIIpmpyleGLLzCK1kA1ZoFgJ/rYZWPfwgi+cqsSBpoIG9Mvfqj www-data@PPE2014

**Comment by RemiLelaidier** [comment]
Normalement c'est bon la

Envoyé de mon ASUS

-------- Message d'origine --------
De :vidavenel <notifications@github.com>
Envoyé :Sun, 14 Feb 2016 11:15:13 +0100
À :RemiLelaidier/SIOC-Silex <SIOC-Silex@noreply.github.com>
Ci :RemiLelaidier <r.lelaidier@hotmail.fr>
Sujet :Re: [SIOC-Silex] auto deploiement (#5)

Non j'ai rien, c'est pas grave tu va le faire:

- Dans webhook tu ajoutes

> adresseDuServeur/deploy_pt.php

- dans deploy key :

> ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7A2IR8ch8OApMgQi2u5KvDWXANEJLJAjHDrqmcVHM7Kd1qhIxTJI1gvZlXuDcw85+Ll9OjDY6M8wBlwhjDPqHF34mtIv51KkSY3j4YVbgnv8ojlVGVAN8ORn1tN5Yvgu/K7cTEq5yGc2sP0zPIalLh9ndodjgMuxz4r4kK/yn0und3IIkLLKsZAC/7aRWOTEWuk7IbWqKJmWSJe9UH0Rh//yJdKUSXXnXzDCU5j0UwcEKXTUASSAXs9eQMSKj922lp5GSs2KsZu7zi/7THJTYC/0BVzc3tJv0PbJIIpmpyleGLLzCK1kA1ZoFgJ/rYZWPfwgi+cqsSBpoIG9Mvfqj www-data@PPE2014

---

**Comment by vidavenel** [comment]
Voila a tester mais normalement a chaque push le serveur se met a jour tt seul sur la branche master

**Comment by vidavenel** [comment]
merci de me tenir au courant

**Comment by RemiLelaidier** [comment]
Je teste ca dans la soirée
