### ISSUE TITLE
Affichage des eleves

### ISSUE THREAD

**Issue by RemiLelaidier** [RemiLelaidier/SIOC-Silex#52]

**Comment by JDLSousa** [comment]
En gros, remettre comme c'était avant quoi ?

**Comment by YokenBabel** [comment]
No c'est bon je crois que c'est fait

**Comment by YokenBabel** [comment]
Oui vient bon c'est les compétences par éleves,
Tu peux cadrer avec la syntaxe de cette page pour les autres !

**Comment by JDLSousa** [comment]
J'ai rien capté.

**Comment by RemiLelaidier** [comment]
Bug d'affichage a Regler, mais la route tourne
