### ISSUE TITLE
VUE/ Lien des edition et suppression

### ISSUE THREAD

**Issue by RemiLelaidier** [RemiLelaidier/SIOC-Silex#55]

**Comment by RemiLelaidier** [comment]
Fait dans la vue Eleve et Professeur

**Comment by JDLSousa** [comment]
Lorsque j'essaye de modifier les infos d'un eleve, j'ai une erreur.

**Comment by RemiLelaidier** [comment]
Fais dans la vue promotion

**Comment by RemiLelaidier** [comment]
Fait dans la vue competence
