### ISSUE TITLE
CONTROLLER/ creation route tableau

### ISSUE THREAD

**Issue by YokenBabel** [RemiLelaidier/SIOC-Silex#56]
TO CHECK

**Comment by RemiLelaidier** [comment]
Pas bon, Demande moi avant de faire un truc dans le controller
Si tu cree une classe uniquement pour une methode, c'est contre productif

**Comment by RemiLelaidier** [comment]
Je deplace la methode dans HomeController

**Comment by YokenBabel** [comment]
Okay d'acc

**Comment by RemiLelaidier** [comment]
fait, tu peux continuer le taf dessus ;)

**Comment by YokenBabel** [comment]
Okay D'ok! Thanks
