### ISSUE TITLE
VUE/ Faire les menu du layout

### ISSUE THREAD

**Issue by RemiLelaidier** [RemiLelaidier/SIOC-Silex#7]
Les menus du layout doivent etre fait.

MENU : 
POUR les eleves
 -Activites
 -Competences
POUR les professeurs 
 -Promotions
 -Eleves
POUR les admins
 Acces a l'onglet utilisateurs

Cette idee de menu est un premier jet, si vous avez de meilleures idees, faites en part dans cette issue

PS : Ne pas oublier de faire en sorte que la navigation soit claire, grace aux menus en surbrillance

**Comment by YokenBabel** [comment]
MENU : 
**élèves**

-**Activites**
--> Visualiser(Visualiser Activés --> Éleves(#id))
--> Gerer(Administration-> Activités(#id) ajouter/supprimer)

-**Competences**
--> Visualiser(Visualiser Compétences --> Éleves(#id))
--> Gerer(Administration --> Compétences(#id) ajouter/supprimer)

**Professeurs**

-**Activités**
--> Visualiser(Visualiser liste --> Activités)
--> Gerer(Administration --> Activités ajouter/supprimer)

-**Competences**
--> Visualiser(Visualiser liste --> compétences)
--> Gerer(Administration --> Compétences ajouter/supprimer)

-**Promotions**
--> Visualiser(Visualiser liste --> Promotions)
--> Gerer(Administration --> Promotions ajouter/supprimer)

-**Éleves**
--> Visualiser(Visualiser liste --> Éleves)
--> Gerer(Administration--> Élèves ajouter/supprimer)

**SuperUser Root Administrator Manager --> GodMode**

-**Activités**
--> Visualiser(Visualiser liste --> Activités)
--> Gerer(Administration --> Activités ajouter/supprimer)

-**Competences**
--> Visualiser(Visualiser liste --> compétences)
--> Gerer(Administration --> Compétences ajouter/supprimer)

-**Promotions**
--> Visualiser(Visualiser liste --> Promotions)
--> Gerer(Administration --> Promotions ajouter/supprimer)

-**Éleves**
--> Visualiser(Visualiser liste --> Éleves)
--> Gerer(Administration--> Élèves ajouter/supprimer)

-**Professeurs**
--> Visualiser(Visualiser liste --> Professeurs)
--> Gerer(Administration --> Professeurs ajouter/supprimer)

**Comment by RemiLelaidier** [comment]
J'approuve ce menu ;)

Pas de difficultes particulieres ?

**Comment by RemiLelaidier** [comment]
Ce que tu as push est a refaire, 
Regarde comment j'ai fait les liens pour le logout et le login. Tu dois utiliser path().
En plus les routes ne sont pas les bonnes, tu peux les rajouter dans le fichier routes.php

Et t'es if app.user, c'est pas comme ca du tout... Il faut utiliser la fonction is_granted associe a un role, le fonctionnement est explique dans la doc de silex->Twig.

Faut ABSOLUMENT que tu lises bien la doc et que tu aprennes a utiliser SIlex.
Tout ca est indique ou alors regarde les tutos sur internet
